name: test

on:
  push:
    branches:
      - "*"
      - "!master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Update version
        env:
          URL: ${{ secrets.VESION_URL }}
          VESION_TOKEN: ${{ secrets.VESION_TOKEN }}
        run: |
          curl \
          -X POST \
          $URL \
          -H "Content-Type: application/json" \
          --data '{ "name": "milvus", "version": "'"${GITHUB_REF#refs/heads/}"'", "commit": "'"${GITHUB_SHA::8}"'", "token": "'"$VESION_TOKEN"'" }'
